version: "3"

vars:
  main_package_path: ./cmd/main.go
  binary_name: link-service

tasks:
  tidy:
    cmds: 
      - go mod tidy -v
      - go fmt ./...

  # Quality Control
  audit:
    desc: run quality control checks
    cmds:
      - go mod tidy -diff
      - go mod verify
      - gofmt -l -d .
      - go vet ./...
      - go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  test:
    deps: [tidy]
    desc: run all tests
    cmds:
      - go test -v -race -buildvcs ./...
  
  test/cover:
    deps: [tidy]
    desc: run all tests and display coverage
    cmds: 
      - go test -v -race -buildvcs -coverprofile=/tmp/coverage.out ./...
      - go tool cover -html=/tmp/coverage.out
    
  # Development
  build:
    desc: build the application
    cmds:
      - go build -o=./tmp/bin/{{.binary_name}} {{.main_package_path}}
  run/dev:
    desc: run the application
    cmds:
      - go run ./cmd/main.go
    env:
      APP_ENV: dev
  run/live:
    desc: run the application with reloading on file changes DOESN'T WORK
    cmds: 
      - go run github.com/cosmtrek/air@v1.43.0 --build.cmd "task build" --build.bin "./tmp/bin/${binary_name}" --build.delay "100" --build.exclude_dir "" --build.include_ext "go, tpl, tmpl, html, css, scss, js, ts, sql, jpeg, jpg, gif, png, bmp, svg, webp, ico" --misc.clean_on_exit "true"

